feature_extract_enable : 0
point_filter_num : 4
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.5 # 0.3
filter_size_map : 0.5 # 0.4
cube_side_length : 1000
debug : 1
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 50
ncc_en: true
ncc_thre: 0.5
img_point_cov : 1000
laser_point_cov : 0.001
cam_fx: 968.05575429
cam_fy: 967.93608947
cam_cx: 638.26584924
cam_cy: 365.97577280

common:
    lid_topic:  "/all_cur_cloud"
    imu_topic:  "/imu/data"
    wheel_odom_topic: "/wheel_odom_to_init"

preprocess:
    lidar_type: 3  # rotating lidar
    scan_line: 64
    blind: 4 # blind x m disable

mapping:
    acc_cov_scale: 0.1 #10
    gyr_cov_scale: 0.1 #10
    fov_degree:    180
    extrinsic_T: [ 0.0, 0.0, 0.0]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

camera:
    img_topic: /camera/image_raw
    Rcl: [0.999250, 0.022676, -0.031411,
         -0.030745, -0.029150, -0.999102,
          -0.023571, 0.999318, -0.028431]
    Pcl: [0.040000, 1.570000, -2.080000]
